using System;
using System.Collections.Generic;

// Token: 0x02000118 RID: 280
public class ItemModifierLibrary : ItemAssetLibrary<ItemModAsset>
{
	// Token: 0x060008A9 RID: 2217 RVA: 0x0007C198 File Offset: 0x0007A398
	public override void init()
	{
		base.init();
		ItemModAsset itemModAsset = new ItemModAsset();
		itemModAsset.id = "normal";
		itemModAsset.mod_type = "normal";
		itemModAsset.pool = "weapon,accessory,armor";
		itemModAsset.rarity = 5;
		itemModAsset.mod_can_be_given = false;
		itemModAsset.has_locales = false;
		ItemModAsset pAsset = itemModAsset;
		this.t = itemModAsset;
		this.add(pAsset);
		ItemModAsset itemModAsset2 = new ItemModAsset();
		itemModAsset2.id = "power1";
		itemModAsset2.mod_type = "power";
		itemModAsset2.translation_key = "mod_power";
		itemModAsset2.rarity = 1;
		itemModAsset2.pool = "weapon";
		itemModAsset2.mod_rank = 1;
		pAsset = itemModAsset2;
		this.t = itemModAsset2;
		this.add(pAsset);
		this.t.base_stats["damage"] = 1f;
		this.clone("power2", "power1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["damage"] = 2f;
		this.clone("power3", "power1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["damage"] = 3f;
		this.clone("power4", "power1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["damage"] = 4f;
		this.clone("power5", "power1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["damage"] = 5f;
		ItemModAsset itemModAsset3 = new ItemModAsset();
		itemModAsset3.id = "truth1";
		itemModAsset3.mod_type = "truth";
		itemModAsset3.translation_key = "mod_truth";
		itemModAsset3.rarity = 1;
		itemModAsset3.pool = "weapon";
		itemModAsset3.mod_rank = 1;
		pAsset = itemModAsset3;
		this.t = itemModAsset3;
		this.add(pAsset);
		this.t.base_stats["diplomacy"] = 1f;
		this.clone("truth2", "truth1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["diplomacy"] = 2f;
		this.clone("truth3", "truth1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["diplomacy"] = 3f;
		this.clone("truth4", "truth1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["diplomacy"] = 4f;
		this.clone("truth5", "truth1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["diplomacy"] = 5f;
		ItemModAsset itemModAsset4 = new ItemModAsset();
		itemModAsset4.id = "protection1";
		itemModAsset4.mod_type = "protection";
		itemModAsset4.translation_key = "mod_protection";
		itemModAsset4.rarity = 1;
		itemModAsset4.pool = "armor";
		pAsset = itemModAsset4;
		this.t = itemModAsset4;
		this.add(pAsset);
		this.t.base_stats["armor"] = 3f;
		this.clone("protection2", "protection1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["armor"] = 4f;
		this.clone("protection3", "protection1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["armor"] = 5f;
		this.clone("protection4", "protection1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["armor"] = 6f;
		this.clone("protection5", "protection1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["armor"] = 7f;
		ItemModAsset itemModAsset5 = new ItemModAsset();
		itemModAsset5.id = "speed1";
		itemModAsset5.mod_type = "speed";
		itemModAsset5.translation_key = "mod_speed";
		itemModAsset5.rarity = 3;
		itemModAsset5.pool = "weapon,accessory,armor";
		pAsset = itemModAsset5;
		this.t = itemModAsset5;
		this.add(pAsset);
		this.t.base_stats["speed"] = 2f;
		this.clone("speed2", "speed1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["speed"] = 3f;
		this.clone("speed3", "speed1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["speed"] = 4f;
		this.clone("speed4", "speed1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["speed"] = 5f;
		this.clone("speed5", "speed1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["speed"] = 6f;
		ItemModAsset itemModAsset6 = new ItemModAsset();
		itemModAsset6.id = "balance1";
		itemModAsset6.mod_type = "balance";
		itemModAsset6.translation_key = "mod_balance";
		itemModAsset6.rarity = 3;
		itemModAsset6.pool = "weapon,accessory,armor";
		pAsset = itemModAsset6;
		this.t = itemModAsset6;
		this.add(pAsset);
		this.t.base_stats["critical_chance"] = 0.05f;
		this.clone("balance2", "balance1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["critical_chance"] = 0.15f;
		this.clone("balance3", "balance1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["critical_chance"] = 0.2f;
		this.clone("balance4", "balance1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["critical_chance"] = 0.25f;
		this.clone("balance5", "balance1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["critical_chance"] = 0.3f;
		ItemModAsset itemModAsset7 = new ItemModAsset();
		itemModAsset7.id = "health1";
		itemModAsset7.mod_type = "health";
		itemModAsset7.translation_key = "mod_health";
		itemModAsset7.rarity = 1;
		itemModAsset7.pool = "armoraccessory";
		pAsset = itemModAsset7;
		this.t = itemModAsset7;
		this.add(pAsset);
		this.t.base_stats["health"] = 50f;
		this.clone("health2", "health1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["health"] = 100f;
		this.clone("health3", "health1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["health"] = 150f;
		this.clone("health4", "health1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["health"] = 200f;
		this.clone("health5", "health1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["health"] = 250f;
		ItemModAsset itemModAsset8 = new ItemModAsset();
		itemModAsset8.id = "finesse1";
		itemModAsset8.mod_type = "finesse";
		itemModAsset8.translation_key = "mod_finesse";
		itemModAsset8.rarity = 1;
		itemModAsset8.pool = "weaponaccessory";
		pAsset = itemModAsset8;
		this.t = itemModAsset8;
		this.add(pAsset);
		this.t.base_stats["attack_speed"] = 1f;
		this.clone("finesse2", "finesse1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["attack_speed"] = 1f;
		this.t.base_stats["speed"] = 1f;
		this.clone("finesse3", "finesse1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["attack_speed"] = 2f;
		this.t.base_stats["speed"] = 1f;
		this.clone("finesse4", "finesse1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["attack_speed"] = 2f;
		this.t.base_stats["speed"] = 2f;
		this.clone("finesse5", "finesse1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["attack_speed"] = 3f;
		this.t.base_stats["speed"] = 3f;
		ItemModAsset itemModAsset9 = new ItemModAsset();
		itemModAsset9.id = "mastery1";
		itemModAsset9.mod_type = "mastery";
		itemModAsset9.translation_key = "mod_mastery";
		itemModAsset9.rarity = 1;
		itemModAsset9.pool = "accessory";
		itemModAsset9.mod_rank = 1;
		pAsset = itemModAsset9;
		this.t = itemModAsset9;
		this.add(pAsset);
		this.t.base_stats["warfare"] = 1f;
		this.clone("mastery2", "mastery1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["warfare"] = 2f;
		this.clone("mastery3", "mastery1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["warfare"] = 3f;
		this.clone("mastery4", "mastery1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["warfare"] = 4f;
		this.clone("mastery5", "mastery1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["warfare"] = 5f;
		ItemModAsset itemModAsset10 = new ItemModAsset();
		itemModAsset10.id = "knowledge1";
		itemModAsset10.mod_type = "knowledge";
		itemModAsset10.translation_key = "mod_knowledge";
		itemModAsset10.rarity = 1;
		itemModAsset10.pool = "accessory";
		itemModAsset10.mod_rank = 1;
		pAsset = itemModAsset10;
		this.t = itemModAsset10;
		this.add(pAsset);
		this.t.base_stats["intelligence"] = 1f;
		this.clone("knowledge2", "knowledge1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["intelligence"] = 2f;
		this.clone("knowledge3", "knowledge1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["intelligence"] = 3f;
		this.clone("knowledge4", "knowledge1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["intelligence"] = 4f;
		this.clone("knowledge5", "knowledge1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["intelligence"] = 7f;
		ItemModAsset itemModAsset11 = new ItemModAsset();
		itemModAsset11.id = "sharpness1";
		itemModAsset11.mod_type = "sharpness";
		itemModAsset11.translation_key = "mod_sharpness";
		itemModAsset11.rarity = 1;
		itemModAsset11.pool = "accessory";
		itemModAsset11.mod_rank = 1;
		pAsset = itemModAsset11;
		this.t = itemModAsset11;
		this.add(pAsset);
		this.t.base_stats["damage"] = 1f;
		this.t.base_stats["multiplier_crit"] = 0.05f;
		this.clone("sharpness2", "sharpness1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 2;
		this.t.base_stats["damage"] = 2f;
		this.t.base_stats["multiplier_crit"] = 0.06f;
		this.clone("sharpness3", "sharpness1");
		this.t.quality = Rarity.R1_Rare;
		this.t.mod_rank = 3;
		this.t.base_stats["damage"] = 3f;
		this.t.base_stats["multiplier_crit"] = 0.08f;
		this.clone("sharpness4", "sharpness1");
		this.t.quality = Rarity.R2_Epic;
		this.t.mod_rank = 4;
		this.t.base_stats["damage"] = 5f;
		this.t.base_stats["multiplier_crit"] = 0.1f;
		this.clone("sharpness5", "sharpness1");
		this.t.quality = Rarity.R3_Legendary;
		this.t.mod_rank = 5;
		this.t.base_stats["damage"] = 10f;
		this.t.base_stats["multiplier_crit"] = 0.1f;
		ItemModAsset itemModAsset12 = new ItemModAsset();
		itemModAsset12.id = "flame";
		itemModAsset12.mod_type = "flame";
		itemModAsset12.translation_key = "mod_flame";
		itemModAsset12.rarity = 0;
		itemModAsset12.pool = "weapon";
		itemModAsset12.mod_rank = 1;
		pAsset = itemModAsset12;
		this.t = itemModAsset12;
		this.add(pAsset);
		this.t.base_stats.addTag("immunity_fire");
		this.t.action_attack_target = new AttackAction(ActionLibrary.addBurningEffectOnTarget);
		this.t.action_special_effect = new WorldAction(ActionLibrary.flamingWeapon);
		this.t.special_effect_interval = 0.1f;
		ItemModAsset itemModAsset13 = new ItemModAsset();
		itemModAsset13.id = "ice";
		itemModAsset13.mod_type = "ice";
		itemModAsset13.translation_key = "mod_ice";
		itemModAsset13.rarity = 0;
		itemModAsset13.pool = "weapon";
		itemModAsset13.mod_rank = 1;
		pAsset = itemModAsset13;
		this.t = itemModAsset13;
		this.add(pAsset);
		this.t.base_stats.addTag("immunity_cold");
		this.t.action_attack_target = new AttackAction(ActionLibrary.addFrozenEffectOnTarget20);
		ItemModAsset itemModAsset14 = new ItemModAsset();
		itemModAsset14.id = "stun";
		itemModAsset14.mod_type = "stun";
		itemModAsset14.translation_key = "mod_stun";
		itemModAsset14.rarity = 0;
		itemModAsset14.pool = "weapon";
		itemModAsset14.mod_rank = 1;
		pAsset = itemModAsset14;
		this.t = itemModAsset14;
		this.add(pAsset);
		this.t.action_attack_target = new AttackAction(ActionLibrary.addStunnedEffectOnTarget20);
		ItemModAsset itemModAsset15 = new ItemModAsset();
		itemModAsset15.id = "slowness";
		itemModAsset15.mod_type = "slowness";
		itemModAsset15.translation_key = "mod_slowness";
		itemModAsset15.rarity = 0;
		itemModAsset15.pool = "weapon";
		itemModAsset15.mod_rank = 1;
		pAsset = itemModAsset15;
		this.t = itemModAsset15;
		this.add(pAsset);
		this.t.action_attack_target = new AttackAction(ActionLibrary.addSlowEffectOnTarget20);
		ItemModAsset itemModAsset16 = new ItemModAsset();
		itemModAsset16.id = "poison";
		itemModAsset16.mod_type = "poison";
		itemModAsset16.translation_key = "mod_poison";
		itemModAsset16.rarity = 0;
		itemModAsset16.pool = "weapon";
		itemModAsset16.mod_rank = 1;
		pAsset = itemModAsset16;
		this.t = itemModAsset16;
		this.add(pAsset);
		this.t.action_attack_target = new AttackAction(ActionLibrary.addPoisonedEffectOnTarget);
		ItemModAsset itemModAsset17 = new ItemModAsset();
		itemModAsset17.id = "eternal";
		itemModAsset17.mod_type = "eternal";
		itemModAsset17.translation_key = "mod_eternal";
		itemModAsset17.rarity = 0;
		itemModAsset17.pool = "weapon,accessory,armor";
		itemModAsset17.mod_rank = 5;
		pAsset = itemModAsset17;
		this.t = itemModAsset17;
		this.add(pAsset);
		ItemModAsset itemModAsset18 = new ItemModAsset();
		itemModAsset18.id = "cursed";
		itemModAsset18.mod_type = "cursed";
		itemModAsset18.translation_key = "mod_cursed";
		itemModAsset18.rarity = 0;
		itemModAsset18.pool = "weapon,accessory,armor";
		itemModAsset18.mod_rank = 5;
		pAsset = itemModAsset18;
		this.t = itemModAsset18;
		this.add(pAsset);
		ItemModAsset itemModAsset19 = new ItemModAsset();
		itemModAsset19.id = "divine_rune";
		itemModAsset19.mod_type = "divine_rune";
		itemModAsset19.translation_key = "divine_rune";
		itemModAsset19.rarity = 0;
		itemModAsset19.pool = "weapon,accessory,armor";
		itemModAsset19.mod_rank = 5;
		pAsset = itemModAsset19;
		this.t = itemModAsset19;
		this.add(pAsset);
	}

	// Token: 0x060008AA RID: 2218 RVA: 0x0007D48C File Offset: 0x0007B68C
	public override void linkAssets()
	{
		base.linkAssets();
		this.pools.Add("weapon", new List<ItemModAsset>());
		this.pools.Add("armor", new List<ItemModAsset>());
		this.pools.Add("accessory", new List<ItemModAsset>());
		foreach (ItemModAsset tAsset in this.list)
		{
			for (int i = 0; i < tAsset.rarity; i++)
			{
				if (tAsset.pool.Contains("weapon"))
				{
					this.pools["weapon"].Add(tAsset);
				}
				if (tAsset.pool.Contains("armor"))
				{
					this.pools["armor"].Add(tAsset);
				}
				if (tAsset.pool.Contains("accessory"))
				{
					this.pools["accessory"].Add(tAsset);
				}
			}
		}
	}

	// Token: 0x040008F2 RID: 2290
	public const string WEAPON = "weapon";

	// Token: 0x040008F3 RID: 2291
	public const string ACCESSORY = "accessory";

	// Token: 0x040008F4 RID: 2292
	public const string ARMOR = "armor";

	// Token: 0x040008F5 RID: 2293
	public const string ALL = "weapon,accessory,armor";

	// Token: 0x040008F6 RID: 2294
	public Dictionary<string, List<ItemModAsset>> pools = new Dictionary<string, List<ItemModAsset>>();
}
