using System;
using Unity.Mathematics;

// Token: 0x020004FC RID: 1276
public class TesterBehTaskLibrary : AssetLibrary<BehaviourTaskTester>
{
	// Token: 0x06002A54 RID: 10836 RVA: 0x0014C32C File Offset: 0x0014A52C
	public override void init()
	{
		base.init();
		BehaviourTaskTester behaviourTaskTester = new BehaviourTaskTester();
		behaviourTaskTester.id = "close_all_windows";
		BehaviourTaskTester pAsset = behaviourTaskTester;
		this.t = behaviourTaskTester;
		this.add(pAsset);
		this.t.addBeh(new TesterBehCloseWindows());
		BehaviourTaskTester behaviourTaskTester2 = new BehaviourTaskTester();
		behaviourTaskTester2.id = "open_random_window";
		pAsset = behaviourTaskTester2;
		this.t = behaviourTaskTester2;
		this.add(pAsset);
		this.t.addBeh(new TesterBehCloseWindows());
		this.t.addBeh(new TesterBehOpenWindow("random"));
		this.t.addBeh(new TesterBehWait(1f));
		BehaviourTaskTester behaviourTaskTester3 = new BehaviourTaskTester();
		behaviourTaskTester3.id = "open_next_window";
		pAsset = behaviourTaskTester3;
		this.t = behaviourTaskTester3;
		this.add(pAsset);
		this.t.addBeh(new TesterBehCloseWindows());
		this.t.addBeh(new TesterBehOpenNextWindow(false, false));
		BehaviourTaskTester behaviourTaskTester4 = new BehaviourTaskTester();
		behaviourTaskTester4.id = "open_next_meta_window";
		pAsset = behaviourTaskTester4;
		this.t = behaviourTaskTester4;
		this.add(pAsset);
		this.t.addBeh(new TesterBehCloseWindows());
		this.t.addBeh(new TesterBehOpenNextWindow(true, false));
		BehaviourTaskTester behaviourTaskTester5 = new BehaviourTaskTester();
		behaviourTaskTester5.id = "open_random_meta_window";
		pAsset = behaviourTaskTester5;
		this.t = behaviourTaskTester5;
		this.add(pAsset);
		this.t.addBeh(new TesterBehCloseWindows());
		this.t.addBeh(new TesterBehOpenNextWindow(true, true));
		BehaviourTaskTester behaviourTaskTester6 = new BehaviourTaskTester();
		behaviourTaskTester6.id = "screenshot_window";
		pAsset = behaviourTaskTester6;
		this.t = behaviourTaskTester6;
		this.add(pAsset);
		this.t.addBeh(new TesterBehScreenshotTooltips(true));
		this.t.addBeh(new TesterBehScreenshotWindow());
		this.t.addBeh(new TesterBehScrollWindow());
		BehaviourTaskTester behaviourTaskTester7 = new BehaviourTaskTester();
		behaviourTaskTester7.id = "test_window_and_tooltips";
		pAsset = behaviourTaskTester7;
		this.t = behaviourTaskTester7;
		this.add(pAsset);
		this.t.addBeh(new TesterBehScreenshotTooltips(false));
		this.t.addBeh(new TesterBehScrollWindow());
		BehaviourTaskTester behaviourTaskTester8 = new BehaviourTaskTester();
		behaviourTaskTester8.id = "setup_window_test";
		pAsset = behaviourTaskTester8;
		this.t = behaviourTaskTester8;
		this.add(pAsset);
		this.t.addBeh(new TesterBehResetTweens());
		this.t.addBeh(new TesterBehSetResolution(562, 1000, "iPhone 7 66x"));
		this.t.addBeh(new TesterBehLoadWorld(1, "mapTemplates/Editor/map_windows"));
		this.t.addBeh(new TesterBehWait(1f));
		this.t.addBeh(new TesterBehSaveWorldIfEmpty(1));
		this.t.addBeh(new TesterBehWait(1f));
		this.t.addBeh(new TesterBehCheckWorld());
		this.t.addBeh(new TesterBehWait(1f));
		BehaviourTaskTester behaviourTaskTester9 = new BehaviourTaskTester();
		behaviourTaskTester9.id = "reset_tweens";
		pAsset = behaviourTaskTester9;
		this.t = behaviourTaskTester9;
		this.add(pAsset);
		this.t.addBeh(new TesterBehResetTweens());
		BehaviourTaskTester behaviourTaskTester10 = new BehaviourTaskTester();
		behaviourTaskTester10.id = "next_language";
		pAsset = behaviourTaskTester10;
		this.t = behaviourTaskTester10;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSetNextLanguage());
		this.t.addBeh(new TesterBehScreenshotFolder());
		BehaviourTaskTester behaviourTaskTester11 = new BehaviourTaskTester();
		behaviourTaskTester11.id = "add_language_file";
		pAsset = behaviourTaskTester11;
		this.t = behaviourTaskTester11;
		this.add(pAsset);
		this.t.addBeh(new TesterBehCopyCurrentLanguage());
		BehaviourTaskTester behaviourTaskTester12 = new BehaviourTaskTester();
		behaviourTaskTester12.id = "prepare_window_testdata";
		pAsset = behaviourTaskTester12;
		this.t = behaviourTaskTester12;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSetupWindowTest());
		BehaviourTaskTester behaviourTaskTester13 = new BehaviourTaskTester();
		behaviourTaskTester13.id = "clear_window_testdata";
		pAsset = behaviourTaskTester13;
		this.t = behaviourTaskTester13;
		this.add(pAsset);
		this.t.addBeh(new TesterBehClearWindowTest());
		this.t.addBeh(new TesterBehCloseWindows());
		BehaviourTaskTester behaviourTaskTester14 = new BehaviourTaskTester();
		behaviourTaskTester14.id = "fill_world_lava";
		pAsset = behaviourTaskTester14;
		this.t = behaviourTaskTester14;
		this.add(pAsset);
		this.t.addBeh(new TesterBehFillWorld("lava0"));
		this.t.addBeh(new TesterBehFillWorld("lava1"));
		this.t.addBeh(new TesterBehFillWorld("lava2"));
		this.t.addBeh(new TesterBehFillWorld("lava3"));
		BehaviourTaskTester behaviourTaskTester15 = new BehaviourTaskTester();
		behaviourTaskTester15.id = "fill_world_pit";
		pAsset = behaviourTaskTester15;
		this.t = behaviourTaskTester15;
		this.add(pAsset);
		for (int i = 0; i < 50; i++)
		{
			this.t.addBeh(new TesterBehFillWorld("pit_close_ocean"));
		}
		BehaviourTaskTester behaviourTaskTester16 = new BehaviourTaskTester();
		behaviourTaskTester16.id = "fill_world_water";
		pAsset = behaviourTaskTester16;
		this.t = behaviourTaskTester16;
		this.add(pAsset);
		for (int j = 0; j < 50; j++)
		{
			this.t.addBeh(new TesterBehFillWorld("deep_ocean"));
		}
		BehaviourTaskTester behaviourTaskTester17 = new BehaviourTaskTester();
		behaviourTaskTester17.id = "fill_world_soil";
		pAsset = behaviourTaskTester17;
		this.t = behaviourTaskTester17;
		this.add(pAsset);
		for (int k = 0; k < 50; k++)
		{
			this.t.addBeh(new TesterBehFillWorld("soil_low"));
		}
		BehaviourTaskTester behaviourTaskTester18 = new BehaviourTaskTester();
		behaviourTaskTester18.id = "fill_world_randomly";
		pAsset = behaviourTaskTester18;
		this.t = behaviourTaskTester18;
		this.add(pAsset);
		for (int l = 0; l < 50; l++)
		{
			this.t.addBeh(new TesterBehFillWorld("random"));
		}
		BehaviourTaskTester behaviourTaskTester19 = new BehaviourTaskTester();
		behaviourTaskTester19.id = "destroy_sim_objects";
		pAsset = behaviourTaskTester19;
		this.t = behaviourTaskTester19;
		this.add(pAsset);
		this.t.addBeh(new TesterBehDestroySimObjects());
		BehaviourTaskTester behaviourTaskTester20 = new BehaviourTaskTester();
		behaviourTaskTester20.id = "end_test";
		pAsset = behaviourTaskTester20;
		this.t = behaviourTaskTester20;
		this.add(pAsset);
		this.t.addBeh(new TesterBehEndJobTest());
		BehaviourTaskTester behaviourTaskTester21 = new BehaviourTaskTester();
		behaviourTaskTester21.id = "restart_test";
		pAsset = behaviourTaskTester21;
		this.t = behaviourTaskTester21;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRestartJobTest());
		BehaviourTaskTester behaviourTaskTester22 = new BehaviourTaskTester();
		behaviourTaskTester22.id = "stop_autotester";
		pAsset = behaviourTaskTester22;
		this.t = behaviourTaskTester22;
		this.add(pAsset);
		this.t.addBeh(new TesterBehEndAutoTester());
		BehaviourTaskTester behaviourTaskTester23 = new BehaviourTaskTester();
		behaviourTaskTester23.id = "shutdown";
		pAsset = behaviourTaskTester23;
		this.t = behaviourTaskTester23;
		this.add(pAsset);
		this.t.addBeh(new TesterBehShutdown());
		BehaviourTaskTester behaviourTaskTester24 = new BehaviourTaskTester();
		behaviourTaskTester24.id = "set_speed_1";
		pAsset = behaviourTaskTester24;
		this.t = behaviourTaskTester24;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Changing game speed"));
		this.t.addBeh(new TesterBehChangeWorldSpeed("x1"));
		BehaviourTaskTester behaviourTaskTester25 = new BehaviourTaskTester();
		behaviourTaskTester25.id = "set_speed_5";
		pAsset = behaviourTaskTester25;
		this.t = behaviourTaskTester25;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Changing game speed"));
		this.t.addBeh(new TesterBehChangeWorldSpeed("x5"));
		BehaviourTaskTester behaviourTaskTester26 = new BehaviourTaskTester();
		behaviourTaskTester26.id = "set_speed_sonic";
		pAsset = behaviourTaskTester26;
		this.t = behaviourTaskTester26;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Changing game speed"));
		this.t.addBeh(new TesterBehChangeWorldSpeed("x40"));
		BehaviourTaskTester behaviourTaskTester27 = new BehaviourTaskTester();
		behaviourTaskTester27.id = "set_speed_sonic_5";
		pAsset = behaviourTaskTester27;
		this.t = behaviourTaskTester27;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Changing game speed"));
		this.t.addBeh(new TesterBehChangeWorldSpeed("x200"));
		BehaviourTaskTester behaviourTaskTester28 = new BehaviourTaskTester();
		behaviourTaskTester28.id = "pause";
		pAsset = behaviourTaskTester28;
		this.t = behaviourTaskTester28;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Pausing game"));
		this.t.addBeh(new TesterBehPause(true));
		BehaviourTaskTester behaviourTaskTester29 = new BehaviourTaskTester();
		behaviourTaskTester29.id = "unpause";
		pAsset = behaviourTaskTester29;
		this.t = behaviourTaskTester29;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Resuming game"));
		this.t.addBeh(new TesterBehPause(false));
		BehaviourTaskTester behaviourTaskTester30 = new BehaviourTaskTester();
		behaviourTaskTester30.id = "setup_laws";
		pAsset = behaviourTaskTester30;
		this.t = behaviourTaskTester30;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Setting up world laws"));
		this.t.addBeh(new TesterBehResetSeeds(123));
		this.t.addBeh(new TesterBehChangeWorldLaw("world_law_hunger", false));
		this.t.addBeh(new TesterBehChangeWorldLaw("world_law_old_age", false));
		BehaviourTaskTester behaviourTaskTester31 = new BehaviourTaskTester();
		behaviourTaskTester31.id = "try_new_city";
		pAsset = behaviourTaskTester31;
		this.t = behaviourTaskTester31;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Spawning 50 units to build a city"));
		this.t.addBeh(new TesterBehFindTileForCity());
		this.t.addBeh(new TesterBehSpawnRandomCivUnit(50, "tile_target"));
		BehaviourTaskTester behaviourTaskTester32 = new BehaviourTaskTester();
		behaviourTaskTester32.id = "wait_for_cities";
		pAsset = behaviourTaskTester32;
		this.t = behaviourTaskTester32;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 3 cities"));
		this.t.addBeh(new TesterBehWaitFor("city", 3));
		BehaviourTaskTester behaviourTaskTester33 = new BehaviourTaskTester();
		behaviourTaskTester33.id = "cull_mobs";
		pAsset = behaviourTaskTester33;
		this.t = behaviourTaskTester33;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRequire("unit", 1000, RequireCondition.AtLeast));
		this.t.addBeh(new TesterBehCullMobs());
		this.t.addBeh(new TesterBehWait(0.5f));
		BehaviourTaskTester behaviourTaskTester34 = new BehaviourTaskTester();
		behaviourTaskTester34.id = "fix_water";
		pAsset = behaviourTaskTester34;
		this.t = behaviourTaskTester34;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRequireUnits("god_finger", 25, RequireCondition.AtMost));
		this.t.addBeh(new TesterBehRequireGroundRatio(0.3f, RequireCondition.AtMost));
		this.t.addBeh(new TesterBehSpawnPowerActor("god_finger", 50));
		BehaviourTaskTester behaviourTaskTester35 = new BehaviourTaskTester();
		behaviourTaskTester35.id = "cull_godfinger";
		pAsset = behaviourTaskTester35;
		this.t = behaviourTaskTester35;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRequireUnits("god_finger", 1, RequireCondition.AtLeast));
		this.t.addBeh(new TesterBehRequireGroundRatio(0.5f, RequireCondition.AtLeast));
		this.t.addBeh(new TesterBehCullUnits("god_finger"));
		BehaviourTaskTester behaviourTaskTester36 = new BehaviourTaskTester();
		behaviourTaskTester36.id = "cull_units";
		pAsset = behaviourTaskTester36;
		this.t = behaviourTaskTester36;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRequire("unit", 1000, RequireCondition.AtLeast));
		this.t.addBeh(new TesterBehClearFavorites());
		this.t.addBeh(new TesterBehSpawnPower("infinity_coin"));
		BehaviourTaskTester behaviourTaskTester37 = new BehaviourTaskTester();
		behaviourTaskTester37.id = "pick_random_meta_objects_graph";
		pAsset = behaviourTaskTester37;
		this.t = behaviourTaskTester37;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Picking random meta objects"));
		this.t.addBeh(new TesterBehSelectRandomMetaObjects(true));
		BehaviourTaskTester behaviourTaskTester38 = new BehaviourTaskTester();
		behaviourTaskTester38.id = "pick_random_meta_objects";
		pAsset = behaviourTaskTester38;
		this.t = behaviourTaskTester38;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSelectRandomMetaObjects(false));
		BehaviourTaskTester behaviourTaskTester39 = new BehaviourTaskTester();
		behaviourTaskTester39.id = "open_gene_editor";
		pAsset = behaviourTaskTester39;
		this.t = behaviourTaskTester39;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Opening subspecies window with gene editor tab"));
		this.t.addBeh(new TesterBehSelectRandomMetaObjects(false));
		this.t.addBeh(new TesterBehOpenWindow("subspecies"));
		this.t.addBeh(new TesterBehOpenWindowTab("Genetics"));
		BehaviourTaskTester behaviourTaskTester40 = new BehaviourTaskTester();
		behaviourTaskTester40.id = "open_city_chart_window";
		pAsset = behaviourTaskTester40;
		this.t = behaviourTaskTester40;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Opening city window with chart tab"));
		this.t.addBeh(new TesterBehOpenWindow("city"));
		this.t.addBeh(new TesterBehOpenWindowTab("Statistics"));
		this.t.addBeh(new TesterBehClickRandomButton(typeof(ButtonGraphCategory)));
		this.t.addBeh(new TesterBehClickRandomButton(typeof(ButtonGraphCategory)));
		this.t.addBeh(new TesterBehClickRandomButton(typeof(ButtonGraphCategory)));
		this.t.addBeh(new TesterBehWait(1f));
		this.t.addBeh(new TesterBehCloseWindows());
		BehaviourTaskTester behaviourTaskTester41 = new BehaviourTaskTester();
		behaviourTaskTester41.id = "open_kingdom_chart_window";
		pAsset = behaviourTaskTester41;
		this.t = behaviourTaskTester41;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Opening kingdom window with chart tab"));
		this.t.addBeh(new TesterBehOpenWindow("kingdom"));
		this.t.addBeh(new TesterBehOpenWindowTab("Statistics"));
		this.t.addBeh(new TesterBehClickRandomButton(typeof(ButtonGraphCategory)));
		this.t.addBeh(new TesterBehClickRandomButton(typeof(ButtonGraphCategory)));
		this.t.addBeh(new TesterBehClickRandomButton(typeof(ButtonGraphCategory)));
		this.t.addBeh(new TesterBehWait(1f));
		this.t.addBeh(new TesterBehCloseWindows());
		BehaviourTaskTester behaviourTaskTester42 = new BehaviourTaskTester();
		behaviourTaskTester42.id = "open_city_window";
		pAsset = behaviourTaskTester42;
		this.t = behaviourTaskTester42;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Opening city window"));
		this.t.addBeh(new TesterBehOpenWindow("city"));
		BehaviourTaskTester behaviourTaskTester43 = new BehaviourTaskTester();
		behaviourTaskTester43.id = "random_meta_switch";
		pAsset = behaviourTaskTester43;
		this.t = behaviourTaskTester43;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRandomMetaSwitch());
		BehaviourTaskTester behaviourTaskTester44 = new BehaviourTaskTester();
		behaviourTaskTester44.id = "open_kingdom_window";
		pAsset = behaviourTaskTester44;
		this.t = behaviourTaskTester44;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Opening kingdom window"));
		this.t.addBeh(new TesterBehOpenWindow("kingdom"));
		BehaviourTaskTester behaviourTaskTester45 = new BehaviourTaskTester();
		behaviourTaskTester45.id = "random_window_tab";
		pAsset = behaviourTaskTester45;
		this.t = behaviourTaskTester45;
		this.add(pAsset);
		this.t.addBeh(new TesterBehRandomWindowTab());
		Random tRand = new Random(100U);
		BehaviourTaskTester behaviourTaskTester46 = new BehaviourTaskTester();
		behaviourTaskTester46.id = "random_bombs_and_kingdoms";
		pAsset = behaviourTaskTester46;
		this.t = behaviourTaskTester46;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Spawning random units and bombs"));
		int tRandomYears = tRand.NextInt(2, 5);
		int tRandomUnits = tRand.NextInt(25, 50);
		this.t.addBeh(new TesterBehWaitYears(tRandomYears));
		this.t.addBeh(new TesterBehWaitForYear());
		this.t.addBeh(new TesterBehLog("Spawning units and bombs"));
		for (int m = 0; m < tRandomUnits; m++)
		{
			this.t.addBeh(new TesterBehSpawnRandomKingdomUnit());
		}
		this.t.addBeh(new TesterBehSpawnRandomBomb());
		BehaviourTaskTester behaviourTaskTester47 = new BehaviourTaskTester();
		behaviourTaskTester47.id = "show_compare_window";
		pAsset = behaviourTaskTester47;
		this.t = behaviourTaskTester47;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Showing chart compare window"));
		this.t.addBeh(new TesterBehOpenWindow("chart_comparer"));
		this.t.addBeh(new TesterBehWait(1f));
		this.t.addBeh(new TesterBehCloseWindows());
		BehaviourTaskTester behaviourTaskTester48 = new BehaviourTaskTester();
		behaviourTaskTester48.id = "wait_05";
		pAsset = behaviourTaskTester48;
		this.t = behaviourTaskTester48;
		this.add(pAsset);
		this.t.addBeh(new TesterBehWait(0.5f));
		BehaviourTaskTester behaviourTaskTester49 = new BehaviourTaskTester();
		behaviourTaskTester49.id = "wait_1";
		pAsset = behaviourTaskTester49;
		this.t = behaviourTaskTester49;
		this.add(pAsset);
		this.t.addBeh(new TesterBehWait(1f));
		BehaviourTaskTester behaviourTaskTester50 = new BehaviourTaskTester();
		behaviourTaskTester50.id = "wait_5";
		pAsset = behaviourTaskTester50;
		this.t = behaviourTaskTester50;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 5 game seconds..."));
		this.t.addBeh(new TesterBehWait(5f));
		BehaviourTaskTester behaviourTaskTester51 = new BehaviourTaskTester();
		behaviourTaskTester51.id = "wait_10";
		pAsset = behaviourTaskTester51;
		this.t = behaviourTaskTester51;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 10 game seconds..."));
		this.t.addBeh(new TesterBehWait(10f));
		BehaviourTaskTester behaviourTaskTester52 = new BehaviourTaskTester();
		behaviourTaskTester52.id = "wait_20";
		pAsset = behaviourTaskTester52;
		this.t = behaviourTaskTester52;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 20 game seconds..."));
		this.t.addBeh(new TesterBehWait(20f));
		BehaviourTaskTester behaviourTaskTester53 = new BehaviourTaskTester();
		behaviourTaskTester53.id = "wait_years_1";
		pAsset = behaviourTaskTester53;
		this.t = behaviourTaskTester53;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 1 year..."));
		this.t.addBeh(new TesterBehWaitYears(1));
		this.t.addBeh(new TesterBehWaitForYear());
		BehaviourTaskTester behaviourTaskTester54 = new BehaviourTaskTester();
		behaviourTaskTester54.id = "wait_years_5";
		pAsset = behaviourTaskTester54;
		this.t = behaviourTaskTester54;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 5 years..."));
		this.t.addBeh(new TesterBehWaitYears(5));
		this.t.addBeh(new TesterBehWaitForYear());
		BehaviourTaskTester behaviourTaskTester55 = new BehaviourTaskTester();
		behaviourTaskTester55.id = "wait_years_10";
		pAsset = behaviourTaskTester55;
		this.t = behaviourTaskTester55;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 10 years..."));
		this.t.addBeh(new TesterBehWaitYears(10));
		this.t.addBeh(new TesterBehWaitForYear());
		BehaviourTaskTester behaviourTaskTester56 = new BehaviourTaskTester();
		behaviourTaskTester56.id = "wait_years_20";
		pAsset = behaviourTaskTester56;
		this.t = behaviourTaskTester56;
		this.add(pAsset);
		this.t.addBeh(new TesterBehLog("Waiting for 20 years..."));
		this.t.addBeh(new TesterBehWaitYears(20));
		this.t.addBeh(new TesterBehWaitForYear());
		BehaviourTaskTester behaviourTaskTester57 = new BehaviourTaskTester();
		behaviourTaskTester57.id = "spawn_random_power";
		pAsset = behaviourTaskTester57;
		this.t = behaviourTaskTester57;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSpawnRandomPower());
		this.t.addBeh(new TesterBehWait(0.1f));
		BehaviourTaskTester behaviourTaskTester58 = new BehaviourTaskTester();
		behaviourTaskTester58.id = "randomize_subspecies_traits";
		pAsset = behaviourTaskTester58;
		this.t = behaviourTaskTester58;
		this.add(pAsset);
		this.t.addBeh(new TesterMutateSubspeciesTraits());
		BehaviourTaskTester behaviourTaskTester59 = new BehaviourTaskTester();
		behaviourTaskTester59.id = "randomize_subspecies_genes";
		pAsset = behaviourTaskTester59;
		this.t = behaviourTaskTester59;
		this.add(pAsset);
		this.t.addBeh(new TesterMutateSubspeciesGenes());
		BehaviourTaskTester behaviourTaskTester60 = new BehaviourTaskTester();
		behaviourTaskTester60.id = "randomize_actor_traits";
		pAsset = behaviourTaskTester60;
		this.t = behaviourTaskTester60;
		this.add(pAsset);
		this.t.addBeh(new TesterMutateActorTraits());
		BehaviourTaskTester behaviourTaskTester61 = new BehaviourTaskTester();
		behaviourTaskTester61.id = "randomize_actor_status";
		pAsset = behaviourTaskTester61;
		this.t = behaviourTaskTester61;
		this.add(pAsset);
		this.t.addBeh(new TesterMutateActorStatus());
		BehaviourTaskTester behaviourTaskTester62 = new BehaviourTaskTester();
		behaviourTaskTester62.id = "spawn_infinity_coin";
		pAsset = behaviourTaskTester62;
		this.t = behaviourTaskTester62;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSpawnPower("infinity_coin"));
		BehaviourTaskTester behaviourTaskTester63 = new BehaviourTaskTester();
		behaviourTaskTester63.id = "spawn_random_unit";
		pAsset = behaviourTaskTester63;
		this.t = behaviourTaskTester63;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSpawnRandomUnit(1, "random"));
		BehaviourTaskTester behaviourTaskTester64 = new BehaviourTaskTester();
		behaviourTaskTester64.id = "spawn_random_unit_5";
		pAsset = behaviourTaskTester64;
		this.t = behaviourTaskTester64;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSpawnRandomUnit(5, "random"));
		BehaviourTaskTester behaviourTaskTester65 = new BehaviourTaskTester();
		behaviourTaskTester65.id = "spawn_random_unit_10";
		pAsset = behaviourTaskTester65;
		this.t = behaviourTaskTester65;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSpawnRandomUnit(10, "random"));
		BehaviourTaskTester behaviourTaskTester66 = new BehaviourTaskTester();
		behaviourTaskTester66.id = "spawn_random_building";
		pAsset = behaviourTaskTester66;
		this.t = behaviourTaskTester66;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSpawnRandomBuilding());
		BehaviourTaskTester behaviourTaskTester67 = new BehaviourTaskTester();
		behaviourTaskTester67.id = "generate_map_random";
		pAsset = behaviourTaskTester67;
		this.t = behaviourTaskTester67;
		this.add(pAsset);
		this.t.addBeh(new TesterBehGenerateMap());
		BehaviourTaskTester behaviourTaskTester68 = new BehaviourTaskTester();
		behaviourTaskTester68.id = "super_damage_units";
		pAsset = behaviourTaskTester68;
		this.t = behaviourTaskTester68;
		this.add(pAsset);
		this.t.addBeh(new TesterBehSuperDamageToUnits());
	}

	// Token: 0x06002A55 RID: 10837 RVA: 0x0014D77E File Offset: 0x0014B97E
	public override void editorDiagnosticLocales()
	{
	}
}
